{% set pkg_name = "epics-seq" %}
{% set pkg_ver = epics_seq %}

package:
  name: {{ pkg_name }}
  version: {{ pkg_ver }}

source:
  url: https://www-csr.bessy.de/control/SoftDist/sequencer/releases/seq-{{ pkg_ver }}.tar.gz

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(pkg_name, max_pin='x.x.x') }}

requirements:
  # re2c is available in conda-forge. You might need '-c conda-forge' to build the package.
  # Sep 8 : By specifying the channel explicitly, we might not have to use '-c conda-forge' anymore
  # https://github.com/conda/conda/issues/988
  host:
    - epics-base {{ epics_base }}
    - re2c [conda-forge]
  run:
    - re2c [conda-forge]

about:
  home: http://www.aps.anl.gov/epics
  license: EPICS Open License (https://epics.anl.gov/license/open.php)

extra:
  maintainers:
   - Saeed Haghtalab <saeed.haghtalab@outlook.com>
   