{% set pkg_name = "epics-std" %}
{% set pkg_ver = epics_std %}

package:
  name: {{ pkg_name }}
  version: {{ pkg_ver }}

source:
  url: https://github.com/epics-modules/std/archive/R{{ pkg_ver | replace(".","-") }}.tar.gz

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(pkg_name, max_pin='x.x.x') }}

requirements:
  host:
    - epics-base {{ epics_base }}
    - epics-asyn {{ epics_asyn }}
    - epics-seq {{ epics_seq }}
      # std has only run-time dependancy to following modules but since conda needs to identify
      # them during the build time, I included them here.
    - epics-calc {{ epics_calc}}
    - epics-busy {{ epics_busy}}
    - epics-sscan {{ epics_sscan }}
    - epics-motor {{ epics_motor }}

about:
  home: http://www.aps.anl.gov/epics
  license: EPICS Open License (https://epics.anl.gov/license/open.php)

extra:
  maintainers:
   - Saeed Haghtalab <saeed.haghtalab@outlook.com>
   